### ISSUE TITLE
DateRange quarter allow future selection over start date

### ISSUE THREAD

**Issue by Dudeplayz** [xdev-software/vaadin-date-range-picker#34]
Hey,
Currently, for the SimpleDateRange Quarter, it is not possible to select a start date which is after the current quarter. This can only be done through the end date. I think for usability it should be possible to select the quarter also over the start date.
I don't know if this is limited by the 'calcForFunc' which only uses one date and not both.

**Comment by AB-xdev** [comment]
@Dudeplayz 
I think you mean that everything in the start-Datepicker is deactivated after the current end-Date and vice versa
![grafik](https://user-images.githubusercontent.com/45384811/96975157-6acbb480-151a-11eb-8e6d-b3019be27a77.png)

This is a safety functionality, because the start should never be after end.
However, theoretically it should be possible to get a working DateRangePicker with that functionality disabled

We could add a option / setting ``setAllowRangeOverlap(boolean)``

**Comment by Dudeplayz** [comment]
Try it with the Year Range. In this case it should be possible to set the Start Date to the next year and adjust the end Date correctly. I think of you set for week, etc. The Start the to the Next Week the end date should adjust, also like the end date. Only for free and kinds of this it shouldnt be allowed.

**Comment by JohannesRabauer** [comment]
Pull-Request https://github.com/xdev-software/vaadin-date-range-picker/pull/105 looks good. I'm creating a seperate branch with the suggested changes, since i can't checkout the existing branch.
