### ISSUE TITLE
DRP overlay closes if clicking with opened DatePicker overlay somewhere else

### ISSUE THREAD

**Issue by Dudeplayz** [xdev-software/vaadin-date-range-picker#47]
Firstly, thanks for the fixes and updates to the DateRangePicker. I really appreciate it 👍.

## Description
The DRP overlay closes if you are clicking out of the DatePicker overlay back into the DRP overlay or on another component. This does not happen if it is closed with a selection or close action.
### GIF
![DateTimePicker](https://user-images.githubusercontent.com/15174076/101042340-606ef280-357d-11eb-8fe3-5aeaace3b7b5.gif)

**Comment by AB-xdev** [comment]
Thank you for your issue.

I also noticed that problem a few days ago in one of our applications.

Vaadin seems to have changed the way how overlays work.

When I now (in 14.4.3) click outside of the opened datepicker (overlay), I get <html> as event target
![HtmlEvent](https://user-images.githubusercontent.com/45384811/101460822-5f054780-393a-11eb-9445-d2b9cb20a795.gif)
![grafik](https://user-images.githubusercontent.com/45384811/101460765-4d23a480-393a-11eb-8881-7965c7f3c598.png)

Before you would get a <... id="overlay"> as event target


This should be fixable by using <body> instead of <html> as root element to listen for click events

**Comment by AB-xdev** [comment]
Should be fixed with the next release
